### ISSUE TITLE
Joystick - Implement throttle lever to regulate turning speed

### ISSUE THREAD

**Issue by bento-bots** [Bento-Robotics/Bento-Box#10]
Right now the turning radius sensitivity is way too high. Please add a regulator.

**Comment by bento-bots** [comment]
Right now the turning radius sensitivity is way too high. Please add a regulator.

**Comment by snaens** [comment]
Fixed in 97d07af through use of [bento_drive](https://github.com/Bento-Robotics/bento_drive) and [bento_teleop](https://github.com/Bento-Robotics/bento_teleop)
